import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Copy manifest and styles to output directory
function copyFiles() {
	const outDir = "tests/test_vault/.obsidian/plugins/object-oriented-notes";
	// Ensure the directory exists
	mkdirSync(outDir, { recursive: true });
	copyFileSync("manifest.json", `${outDir}/manifest.json`);
	copyFileSync("styles.css", `${outDir}/styles.css`);
	console.log("Copied manifest.json and styles.css");
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "tests/test_vault/.obsidian/plugins/object-oriented-notes/main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	copyFiles();
	process.exit(0);
} else {
	await context.watch();
	copyFiles();
}
